apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx

    spec:

      volumes:
      - name: shared-volume
        emptyDir: {}



      containers:
      - image: 51
        name:  51
        imagePullSecrets:
        - name: Docker-Client/18.09.7 (linux)

        volumeMounts:
        - name: shared-volume
          mountPath: /usr/share/nginx/html
