apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx

    spec:

      volumes:
      - name: shared-volume
        emptyDir: {}



      containers:
      - image: localhost:5000/ubuntu
        name:  localhost:5000/ubuntu 


        volumeMounts:
        - name: shared-volume
          mountPath: /usr/share/nginx/html
